CREATE OR REPLACE VIEW vInfosBanc AS
  SELECT A.COD_AGENCIA, 
         A.NOME AS NOME_AGENCIA,
         C.NRO_CONTA,
         C.NOME,
         C.SALDO
  FROM CONTA C, AGENCIA A
  WHERE C.COD_AGENCIA = A.COD_AGENCIA
