CREATE OR REPLACE VIEW vDadosAg AS 
  SELECT C.COD_AGENCIA, 
         A.NOME AS NOME_AGENCIA,
         COUNT(*) AS QTDE_CONTAS,
         MIN(SALDO) AS SALDO_MINIMO,
         MAX(SALDO) AS SALDO_MAXIMO,
         ROUND(AVG(SALDO),2) AS SALDO_MEDIO
  FROM CONTA C, AGENCIA A
  WHERE C.COD_AGENCIA = A.COD_AGENCIA
  GROUP BY C.COD_AGENCIA, A.NOME
