SELECT AC.COD_APLICACAO, AP.DESCRICAO, ROUND(AC.TOT_COTAS * CO.VALOR_COTA, 2) AS TOT_APLIC
FROM (SELECT AC.COD_APLICACAO, SUM(AC.NRO_COTAS) AS TOT_COTAS
      FROM APLIC_CONTA AC
      GROUP BY AC.COD_APLICACAO
     ) AC
  JOIN 
     (SELECT CO.COD_APLICACAO, CO.VALOR_COTA
      FROM APLIC_COTA CO
      WHERE CO.DATA = (SELECT MAX(DATA) 
                       FROM APLIC_COTA                  
                       WHERE COD_APLICACAO = CO.COD_APLICACAO)
     ) CO
     ON AC.COD_APLICACAO = CO.COD_APLICACAO
  JOIN APLICACAO AP
     ON AC.COD_APLICACAO = AP.COD_APLICACAO
ORDER BY AC.COD_APLICACAO