SELECT A.COD_APLICACAO, A.DESCRICAO, 
       ROUND(APLIC.TOT_COTAS * CO.VALOR_COTA,2) AS TOT_APLIC
FROM APLICACAO A 
  JOIN (SELECT AC.COD_APLICACAO, SUM(AC.NRO_COTAS) AS TOT_COTAS
        FROM APLIC_CONTA AC
        GROUP BY AC.COD_APLICACAO
       ) APLIC
    ON A.COD_APLICACAO = APLIC.COD_APLICACAO
  JOIN (SELECT COD_APLICACAO, MAX(DATA) AS MAIOR_DATA
        FROM APLIC_COTA
        GROUP BY COD_APLICACAO
       ) MAIOR
    ON A.COD_APLICACAO = MAIOR.COD_APLICACAO
  JOIN APLIC_COTA CO
    ON CO.COD_APLICACAO = MAIOR.COD_APLICACAO
      AND CO.DATA = MAIOR.MAIOR_DATA 
ORDER BY A.COD_APLICACAO    
