SELECT C.NRO_CONTA, C.NOME, C.SALDO, 
       COALESCE(ROUND(SUM(AC.NRO_COTAS * CO.VALOR_COTA),2),0) AS VLR_APLIC
FROM CONTA C
  LEFT JOIN APLIC_CONTA AC ON C.NRO_CONTA = AC.NRO_CONTA
  LEFT JOIN (SELECT CO.COD_APLICACAO, CO.VALOR_COTA
             FROM APLIC_COTA CO
             WHERE CO.DATA = (SELECT MAX(DATA) 
                              FROM APLIC_COTA                  
                              WHERE COD_APLICACAO = CO.COD_APLICACAO)
            ) CO
     ON AC.COD_APLICACAO = CO.COD_APLICACAO
GROUP BY C.NRO_CONTA, C.NOME, C.SALDO
ORDER BY C.NRO_CONTA;
