SELECT C.NRO_CONTA, C.NOME, C.SALDO, 
       COALESCE(ROUND(SUM(AC.NRO_COTAS * CO.VALOR_COTA),2),0) AS VLR_APLIC
FROM CONTA C
  LEFT JOIN APLIC_CONTA AC ON C.NRO_CONTA = AC.NRO_CONTA
  LEFT JOIN (SELECT COD_APLICACAO, MAX(DATA) AS MAIOR_DATA
             FROM APLIC_COTA
             GROUP BY COD_APLICACAO
            ) MAIOR
    ON AC.COD_APLICACAO = MAIOR.COD_APLICACAO
  LEFT JOIN APLIC_COTA CO
    ON CO.COD_APLICACAO = MAIOR.COD_APLICACAO
      AND CO.DATA = MAIOR.MAIOR_DATA 
GROUP BY C.NRO_CONTA, C.NOME, C.SALDO
ORDER BY C.NRO_CONTA;

